name: Deploy Hexo to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

# ✅ 关键：给 github-actions[bot] 赋予推送权限
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.20.0   # 保持与你本地一致

      - name: Install dependencies
        run: npm install

      - name: Build Hexo
        run: npx hexo generate

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
